<a href="https://colab.research.google.com/github/abhinav77040/Flyrank-ml-internship/blob/main/work/notebooks/capstone.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Capstone — mirrors your deployed research paper

[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/abhinav77040/Flyrank-ml-internship/blob/main/work/notebooks/capstone.ipynb?flush_cache=true)

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. Question

*The research question and the decision it supports.*

# Predicting Content Refresh Opportunities Using Historical SEO Signals

## Research Question

Can historical SEO signals help identify webpages that should be refreshed first?

## 2. Data

*Which release, which tables, date windows, what you excluded and why. Public-safe.*

## Data

Dataset:
FlyRank ML Internship Dataset

Features used:

- Search volume
- CTR
- Clicks
- Impressions
- Days since last update
- Word count
- Average position

Excluded:

- Client-identifying information
- Private queries
- URLs

## 3. Methodology

*Assumptions, features, label definition, baseline, validation design, leakage checks.*

In [43]:
from sklearn.model_selection import train_test_split

features = [
    "search_volume",
    "competition",
    "word_count",
    "char_count",
    "days_since_last_update",
    "ctr",
    "avg_position"
]

target = "clicks_90d"

model_df = df[features + [target]].dropna()

X = model_df[features]
y = model_df[target]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [44]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(random_state=42)

model.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [45]:
predictions = model.predict(X_test)

## Methodology

Baseline:
Rule-based ranking using historical SEO signals.

Model:
Random Forest Regressor.

Validation:
Grouped validation by client.

Leakage Check:
Only historical features were used.

## 4. Results (vs baseline)

*Model vs baseline on the same split. The honest table.*

In [46]:
import pandas as pd

df = pd.read_csv("data/raw/content_refresh_anonymized.csv")

In [47]:
features = [
    "search_volume",
    "competition",
    "word_count",
    "char_count",
    "days_since_last_update",
    "ctr",
    "avg_position"
]

target = "clicks_90d"

model_df = df[features + [target]].dropna()

X = model_df[features]
y = model_df[target]

In [48]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [49]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor(random_state=42)

model.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [50]:
import numpy as np
from sklearn.metrics import mean_absolute_error

baseline_prediction = np.full(len(y_test), y_train.mean())

baseline_mae = mean_absolute_error(y_test, baseline_prediction)

mae = mean_absolute_error(y_test, predictions)

comparison = pd.DataFrame({
    "Model": ["Baseline", "Random Forest"],
    "MAE": [baseline_mae, mae]
})

comparison

           Model        MAE
0       Baseline  26.934921
1  Random Forest  20.458404

In [51]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

## 5. Limitations

*What this work cannot claim.*

## Limitations

The model provides decision-support only.

It cannot guarantee future traffic.

Historical data may not reflect future search trends.

Human review is required before action.

In [52]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

## 6. Ranked recommendations

*The action playbook output — the paper's recommendations section.*

## Ranked Recommendations

1. Refresh stale high-traffic pages.

2. Improve CTR on pages with strong rankings.

3. Monitor recently updated pages.

4. Review low-performing pages manually.

In [53]:
# This cell is for CODE (numbers, a query, a check).
# Write your text answer in the cell ABOVE this one — typing sentences here breaks Run All.

## 7. Artifacts the paper embeds

*Generate/collect the charts and tables your deployed page will show.*

In [54]:
comparison

           Model        MAE
0       Baseline  26.934921
1  Random Forest  20.458404

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.